<h2>Order Confirmation</h2>
<table>
    <tr>
        <td><b>Status:</b></td>
        <td>${data.status}</td>
    </tr>
    <tr>
        <td><b>Name:</b></td>
        <td>${data.item.name}</td>
    </tr>
    <tr>
        <td><b>Price:</b></td>
        <td>${data.item.price}</td>
    </tr>
    <tr>
        <td><b>Quantity:</b></td>
        <td>${data.item.quantity}</td>
    </tr>
</table>
